/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'id' : string,
  'active' : boolean,
  'owner' : Principal,
  'agentType' : AgentType,
  'lastRun' : bigint,
}
export type AgentType = { 'habit' : null } |
  { 'copy' : null } |
  { 'analytics' : null } |
  { 'affiliate' : null };
export interface AppLicense {
  'expiresAt' : [] | [Time],
  'purchaseTime' : Time,
  'owner' : Principal,
  'licenseType' : LicenseType,
}
export interface AutomationStatus {
  'totalExecutions' : bigint,
  'lastRun' : [] | [Time],
  'running' : boolean,
}
export interface CloneProtectionSettings {
  'cloneProtectionEnabled' : boolean,
  'demoModeEnabled' : boolean,
  'sellingPriceCents' : bigint,
}
export type ContentType = { 'performanceData' : null } |
  { 'strategy' : null } |
  { 'insight' : null } |
  { 'recommendation' : null };
export interface KnowledgeEntry {
  'id' : string,
  'references' : Array<Reference>,
  'content' : string,
  'contentType' : ContentType,
  'owner' : Principal,
  'sourceAgent' : AgentType,
  'timestamp' : Time,
}
export type LaunchRecord = {};
export type LicenseType = { 'trial' : null } |
  { 'demo' : null } |
  { 'full' : null };
export type LogEntry = string;
export interface Offer {
  'id' : string,
  'endDate' : [] | [Time],
  'productId' : string,
  'commissionRate' : number,
  'priceInCents' : bigint,
  'startDate' : Time,
}
export interface OfferPerformanceMetrics {
  'lastUpdated' : Time,
  'clickCount' : bigint,
  'revenueTotal' : bigint,
  'conversionRate' : number,
}
export interface Reference { 'refType' : ContentType, 'refId' : string }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLaunch' : ActorMethod<[string, Time], undefined>,
  'addOffer' : ActorMethod<[string, bigint, number, Time, [] | [Time]], string>,
  'addOfferMetrics' : ActorMethod<[string, bigint, number, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgent' : ActorMethod<[AgentType], string>,
  'createAppLicense' : ActorMethod<[LicenseType], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAgent' : ActorMethod<[string], undefined>,
  'getAgent' : ActorMethod<[string], [] | [Agent]>,
  'getAgentLogs' : ActorMethod<[AgentType], Array<LogEntry>>,
  'getAllAgentLogs' : ActorMethod<
    [],
    {
      'habit' : Array<LogEntry>,
      'copy' : Array<LogEntry>,
      'analytics' : Array<LogEntry>,
      'affiliate' : Array<LogEntry>,
    }
  >,
  'getAllAgents' : ActorMethod<[], Array<Agent>>,
  'getAllAppLicenses' : ActorMethod<[], Array<AppLicense>>,
  'getAllAutomationStatuses' : ActorMethod<
    [],
    Array<[AgentType, AutomationStatus]>
  >,
  'getAllKnowledgeEntries' : ActorMethod<[], Array<KnowledgeEntry>>,
  'getAllLaunches' : ActorMethod<[], Array<LaunchRecord>>,
  'getAllOfferMetrics' : ActorMethod<[], Array<OfferPerformanceMetrics>>,
  'getAllOffers' : ActorMethod<[], Array<Offer>>,
  'getAutomationStatus' : ActorMethod<[AgentType], AutomationStatus>,
  'getCallerAgents' : ActorMethod<[], Array<Agent>>,
  'getCallerAppLicense' : ActorMethod<[], [] | [AppLicense]>,
  'getCallerKnowledgeEntries' : ActorMethod<[], Array<KnowledgeEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClickCountPerOffer' : ActorMethod<[], Array<[string, bigint]>>,
  'getCloneProtectionSettings' : ActorMethod<[], CloneProtectionSettings>,
  'getCollaborationStats' : ActorMethod<[], Array<[AgentType, bigint]>>,
  'getConversionRatePerOffer' : ActorMethod<[], Array<[string, number]>>,
  'getIsStripeReady' : ActorMethod<[], boolean>,
  'getKnowledgeEntry' : ActorMethod<[string], [] | [KnowledgeEntry]>,
  'getOfferMetrics' : ActorMethod<[string], [] | [OfferPerformanceMetrics]>,
  'getOfferPerformanceSummary' : ActorMethod<
    [],
    {
      'totalOffers' : bigint,
      'revenueTotals' : bigint,
      'conversionRates' : Array<[string, number]>,
      'allMetrics' : Array<OfferPerformanceMetrics>,
      'clickCounts' : Array<[string, bigint]>,
    }
  >,
  'getRevenueTotals' : ActorMethod<[], bigint>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalActiveOffers' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initStripe' : ActorMethod<[string], undefined>,
  'isActiveUser' : ActorMethod<[], boolean>,
  'isAuthorizedClone' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOwnerCertified' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'runAffiliateAgent' : ActorMethod<[], undefined>,
  'runAgent' : ActorMethod<[AgentType], undefined>,
  'runAgentId' : ActorMethod<[string], undefined>,
  'runAllAgents' : ActorMethod<[], undefined>,
  'runAnalyticsAgent' : ActorMethod<[], undefined>,
  'runCollaborationLoop' : ActorMethod<[], undefined>,
  'runCopyAgent' : ActorMethod<[], undefined>,
  'runHabitAgent' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'startRecurringTimer' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAgent' : ActorMethod<[string, boolean], undefined>,
  'updateCloneProtection' : ActorMethod<[CloneProtectionSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];