/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgentType = IDL.Variant({
  'habit' : IDL.Null,
  'copy' : IDL.Null,
  'analytics' : IDL.Null,
  'affiliate' : IDL.Null,
});
export const LicenseType = IDL.Variant({
  'trial' : IDL.Null,
  'demo' : IDL.Null,
  'full' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Agent = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'owner' : IDL.Principal,
  'agentType' : AgentType,
  'lastRun' : IDL.Int,
});
export const LogEntry = IDL.Text;
export const AppLicense = IDL.Record({
  'expiresAt' : IDL.Opt(Time),
  'purchaseTime' : Time,
  'owner' : IDL.Principal,
  'licenseType' : LicenseType,
});
export const AutomationStatus = IDL.Record({
  'totalExecutions' : IDL.Nat,
  'lastRun' : IDL.Opt(Time),
  'running' : IDL.Bool,
});
export const ContentType = IDL.Variant({
  'performanceData' : IDL.Null,
  'strategy' : IDL.Null,
  'insight' : IDL.Null,
  'recommendation' : IDL.Null,
});
export const Reference = IDL.Record({
  'refType' : ContentType,
  'refId' : IDL.Text,
});
export const KnowledgeEntry = IDL.Record({
  'id' : IDL.Text,
  'references' : IDL.Vec(Reference),
  'content' : IDL.Text,
  'contentType' : ContentType,
  'owner' : IDL.Principal,
  'sourceAgent' : AgentType,
  'timestamp' : Time,
});
export const LaunchRecord = IDL.Record({});
export const OfferPerformanceMetrics = IDL.Record({
  'lastUpdated' : Time,
  'clickCount' : IDL.Nat,
  'revenueTotal' : IDL.Nat,
  'conversionRate' : IDL.Float64,
});
export const Offer = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'productId' : IDL.Text,
  'commissionRate' : IDL.Float64,
  'priceInCents' : IDL.Nat,
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const CloneProtectionSettings = IDL.Record({
  'cloneProtectionEnabled' : IDL.Bool,
  'demoModeEnabled' : IDL.Bool,
  'sellingPriceCents' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLaunch' : IDL.Func([IDL.Text, Time], [], []),
  'addOffer' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, Time, IDL.Opt(Time)],
      [IDL.Text],
      [],
    ),
  'addOfferMetrics' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgent' : IDL.Func([AgentType], [IDL.Text], []),
  'createAppLicense' : IDL.Func([LicenseType], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAgent' : IDL.Func([IDL.Text], [], []),
  'getAgent' : IDL.Func([IDL.Text], [IDL.Opt(Agent)], ['query']),
  'getAgentLogs' : IDL.Func([AgentType], [IDL.Vec(LogEntry)], ['query']),
  'getAllAgentLogs' : IDL.Func(
      [],
      [
        IDL.Record({
          'habit' : IDL.Vec(LogEntry),
          'copy' : IDL.Vec(LogEntry),
          'analytics' : IDL.Vec(LogEntry),
          'affiliate' : IDL.Vec(LogEntry),
        }),
      ],
      ['query'],
    ),
  'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getAllAppLicenses' : IDL.Func([], [IDL.Vec(AppLicense)], ['query']),
  'getAllAutomationStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(AgentType, AutomationStatus))],
      ['query'],
    ),
  'getAllKnowledgeEntries' : IDL.Func([], [IDL.Vec(KnowledgeEntry)], ['query']),
  'getAllLaunches' : IDL.Func([], [IDL.Vec(LaunchRecord)], ['query']),
  'getAllOfferMetrics' : IDL.Func(
      [],
      [IDL.Vec(OfferPerformanceMetrics)],
      ['query'],
    ),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getAutomationStatus' : IDL.Func([AgentType], [AutomationStatus], ['query']),
  'getCallerAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getCallerAppLicense' : IDL.Func([], [IDL.Opt(AppLicense)], ['query']),
  'getCallerKnowledgeEntries' : IDL.Func(
      [],
      [IDL.Vec(KnowledgeEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClickCountPerOffer' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getCloneProtectionSettings' : IDL.Func(
      [],
      [CloneProtectionSettings],
      ['query'],
    ),
  'getCollaborationStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(AgentType, IDL.Nat))],
      ['query'],
    ),
  'getConversionRatePerOffer' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getIsStripeReady' : IDL.Func([], [IDL.Bool], ['query']),
  'getKnowledgeEntry' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(KnowledgeEntry)],
      ['query'],
    ),
  'getOfferMetrics' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(OfferPerformanceMetrics)],
      ['query'],
    ),
  'getOfferPerformanceSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalOffers' : IDL.Nat,
          'revenueTotals' : IDL.Nat,
          'conversionRates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
          'allMetrics' : IDL.Vec(OfferPerformanceMetrics),
          'clickCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'getRevenueTotals' : IDL.Func([], [IDL.Nat], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalActiveOffers' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initStripe' : IDL.Func([IDL.Text], [], []),
  'isActiveUser' : IDL.Func([], [IDL.Bool], ['query']),
  'isAuthorizedClone' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwnerCertified' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'runAffiliateAgent' : IDL.Func([], [], []),
  'runAgent' : IDL.Func([AgentType], [], []),
  'runAgentId' : IDL.Func([IDL.Text], [], []),
  'runAllAgents' : IDL.Func([], [], []),
  'runAnalyticsAgent' : IDL.Func([], [], []),
  'runCollaborationLoop' : IDL.Func([], [], []),
  'runCopyAgent' : IDL.Func([], [], []),
  'runHabitAgent' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'startRecurringTimer' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAgent' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateCloneProtection' : IDL.Func([CloneProtectionSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AgentType = IDL.Variant({
    'habit' : IDL.Null,
    'copy' : IDL.Null,
    'analytics' : IDL.Null,
    'affiliate' : IDL.Null,
  });
  const LicenseType = IDL.Variant({
    'trial' : IDL.Null,
    'demo' : IDL.Null,
    'full' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Agent = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'owner' : IDL.Principal,
    'agentType' : AgentType,
    'lastRun' : IDL.Int,
  });
  const LogEntry = IDL.Text;
  const AppLicense = IDL.Record({
    'expiresAt' : IDL.Opt(Time),
    'purchaseTime' : Time,
    'owner' : IDL.Principal,
    'licenseType' : LicenseType,
  });
  const AutomationStatus = IDL.Record({
    'totalExecutions' : IDL.Nat,
    'lastRun' : IDL.Opt(Time),
    'running' : IDL.Bool,
  });
  const ContentType = IDL.Variant({
    'performanceData' : IDL.Null,
    'strategy' : IDL.Null,
    'insight' : IDL.Null,
    'recommendation' : IDL.Null,
  });
  const Reference = IDL.Record({ 'refType' : ContentType, 'refId' : IDL.Text });
  const KnowledgeEntry = IDL.Record({
    'id' : IDL.Text,
    'references' : IDL.Vec(Reference),
    'content' : IDL.Text,
    'contentType' : ContentType,
    'owner' : IDL.Principal,
    'sourceAgent' : AgentType,
    'timestamp' : Time,
  });
  const LaunchRecord = IDL.Record({});
  const OfferPerformanceMetrics = IDL.Record({
    'lastUpdated' : Time,
    'clickCount' : IDL.Nat,
    'revenueTotal' : IDL.Nat,
    'conversionRate' : IDL.Float64,
  });
  const Offer = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'productId' : IDL.Text,
    'commissionRate' : IDL.Float64,
    'priceInCents' : IDL.Nat,
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const CloneProtectionSettings = IDL.Record({
    'cloneProtectionEnabled' : IDL.Bool,
    'demoModeEnabled' : IDL.Bool,
    'sellingPriceCents' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLaunch' : IDL.Func([IDL.Text, Time], [], []),
    'addOffer' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, Time, IDL.Opt(Time)],
        [IDL.Text],
        [],
      ),
    'addOfferMetrics' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgent' : IDL.Func([AgentType], [IDL.Text], []),
    'createAppLicense' : IDL.Func([LicenseType], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAgent' : IDL.Func([IDL.Text], [], []),
    'getAgent' : IDL.Func([IDL.Text], [IDL.Opt(Agent)], ['query']),
    'getAgentLogs' : IDL.Func([AgentType], [IDL.Vec(LogEntry)], ['query']),
    'getAllAgentLogs' : IDL.Func(
        [],
        [
          IDL.Record({
            'habit' : IDL.Vec(LogEntry),
            'copy' : IDL.Vec(LogEntry),
            'analytics' : IDL.Vec(LogEntry),
            'affiliate' : IDL.Vec(LogEntry),
          }),
        ],
        ['query'],
      ),
    'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getAllAppLicenses' : IDL.Func([], [IDL.Vec(AppLicense)], ['query']),
    'getAllAutomationStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AgentType, AutomationStatus))],
        ['query'],
      ),
    'getAllKnowledgeEntries' : IDL.Func(
        [],
        [IDL.Vec(KnowledgeEntry)],
        ['query'],
      ),
    'getAllLaunches' : IDL.Func([], [IDL.Vec(LaunchRecord)], ['query']),
    'getAllOfferMetrics' : IDL.Func(
        [],
        [IDL.Vec(OfferPerformanceMetrics)],
        ['query'],
      ),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getAutomationStatus' : IDL.Func(
        [AgentType],
        [AutomationStatus],
        ['query'],
      ),
    'getCallerAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getCallerAppLicense' : IDL.Func([], [IDL.Opt(AppLicense)], ['query']),
    'getCallerKnowledgeEntries' : IDL.Func(
        [],
        [IDL.Vec(KnowledgeEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClickCountPerOffer' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getCloneProtectionSettings' : IDL.Func(
        [],
        [CloneProtectionSettings],
        ['query'],
      ),
    'getCollaborationStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AgentType, IDL.Nat))],
        ['query'],
      ),
    'getConversionRatePerOffer' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getIsStripeReady' : IDL.Func([], [IDL.Bool], ['query']),
    'getKnowledgeEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(KnowledgeEntry)],
        ['query'],
      ),
    'getOfferMetrics' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(OfferPerformanceMetrics)],
        ['query'],
      ),
    'getOfferPerformanceSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalOffers' : IDL.Nat,
            'revenueTotals' : IDL.Nat,
            'conversionRates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
            'allMetrics' : IDL.Vec(OfferPerformanceMetrics),
            'clickCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'getRevenueTotals' : IDL.Func([], [IDL.Nat], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalActiveOffers' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initStripe' : IDL.Func([IDL.Text], [], []),
    'isActiveUser' : IDL.Func([], [IDL.Bool], ['query']),
    'isAuthorizedClone' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwnerCertified' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'runAffiliateAgent' : IDL.Func([], [], []),
    'runAgent' : IDL.Func([AgentType], [], []),
    'runAgentId' : IDL.Func([IDL.Text], [], []),
    'runAllAgents' : IDL.Func([], [], []),
    'runAnalyticsAgent' : IDL.Func([], [], []),
    'runCollaborationLoop' : IDL.Func([], [], []),
    'runCopyAgent' : IDL.Func([], [], []),
    'runHabitAgent' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'startRecurringTimer' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAgent' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateCloneProtection' : IDL.Func([CloneProtectionSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };