/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface AutomationStatus {
    totalExecutions: bigint;
    lastRun?: Time;
    running: boolean;
}
export interface KnowledgeEntry {
    id: string;
    references: Array<Reference>;
    content: string;
    contentType: ContentType;
    owner: Principal;
    sourceAgent: AgentType;
    timestamp: Time;
}
export interface Agent {
    id: string;
    active: boolean;
    owner: Principal;
    agentType: AgentType;
    lastRun: bigint;
}
export interface LaunchRecord {
}
export interface OfferPerformanceMetrics {
    lastUpdated: Time;
    clickCount: bigint;
    revenueTotal: bigint;
    conversionRate: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type LogEntry = string;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Offer {
    id: string;
    endDate?: Time;
    productId: string;
    commissionRate: number;
    priceInCents: bigint;
    startDate: Time;
}
export interface CloneProtectionSettings {
    cloneProtectionEnabled: boolean;
    demoModeEnabled: boolean;
    sellingPriceCents: bigint;
}
export interface AppLicense {
    expiresAt?: Time;
    purchaseTime: Time;
    owner: Principal;
    licenseType: LicenseType;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Reference {
    refType: ContentType;
    refId: string;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export enum AgentType {
    habit = "habit",
    copy = "copy",
    analytics = "analytics",
    affiliate = "affiliate"
}
export enum ContentType {
    performanceData = "performanceData",
    strategy = "strategy",
    insight = "insight",
    recommendation = "recommendation"
}
export enum LicenseType {
    trial = "trial",
    demo = "demo",
    full = "full"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLaunch(_cloneId: string, _launchTime: Time): Promise<void>;
    addOffer(productId: string, priceInCents: bigint, commissionRate: number, startDate: Time, endDate: Time | null): Promise<string>;
    addOfferMetrics(offerId: string, clickCount: bigint, conversionRate: number, revenueTotal: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAgent(agentType: AgentType): Promise<string>;
    createAppLicense(licenseType: LicenseType): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteAgent(agentId: string): Promise<void>;
    getAgent(agentId: string): Promise<Agent | null>;
    getAgentLogs(agentType: AgentType): Promise<Array<LogEntry>>;
    getAllAgentLogs(): Promise<{
        habit: Array<LogEntry>;
        copy: Array<LogEntry>;
        analytics: Array<LogEntry>;
        affiliate: Array<LogEntry>;
    }>;
    getAllAgents(): Promise<Array<Agent>>;
    getAllAppLicenses(): Promise<Array<AppLicense>>;
    getAllAutomationStatuses(): Promise<Array<[AgentType, AutomationStatus]>>;
    getAllKnowledgeEntries(): Promise<Array<KnowledgeEntry>>;
    getAllLaunches(): Promise<Array<LaunchRecord>>;
    getAllOfferMetrics(): Promise<Array<OfferPerformanceMetrics>>;
    getAllOffers(): Promise<Array<Offer>>;
    getAutomationStatus(agentType: AgentType): Promise<AutomationStatus>;
    getCallerAgents(): Promise<Array<Agent>>;
    getCallerAppLicense(): Promise<AppLicense | null>;
    getCallerKnowledgeEntries(): Promise<Array<KnowledgeEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClickCountPerOffer(): Promise<Array<[string, bigint]>>;
    getCloneProtectionSettings(): Promise<CloneProtectionSettings>;
    getCollaborationStats(): Promise<Array<[AgentType, bigint]>>;
    getConversionRatePerOffer(): Promise<Array<[string, number]>>;
    getIsStripeReady(): Promise<boolean>;
    getKnowledgeEntry(entryId: string): Promise<KnowledgeEntry | null>;
    getOfferMetrics(offerId: string): Promise<OfferPerformanceMetrics | null>;
    getOfferPerformanceSummary(): Promise<{
        totalOffers: bigint;
        revenueTotals: bigint;
        conversionRates: Array<[string, number]>;
        allMetrics: Array<OfferPerformanceMetrics>;
        clickCounts: Array<[string, bigint]>;
    }>;
    getRevenueTotals(): Promise<bigint>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTotalActiveOffers(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initStripe(secretKey: string): Promise<void>;
    isActiveUser(): Promise<boolean>;
    isAuthorizedClone(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isOwnerCertified(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    runAffiliateAgent(): Promise<void>;
    runAgent(agentType: AgentType): Promise<void>;
    runAgentId(agentId: string): Promise<void>;
    runAllAgents(): Promise<void>;
    runAnalyticsAgent(): Promise<void>;
    runCollaborationLoop(): Promise<void>;
    runCopyAgent(): Promise<void>;
    runHabitAgent(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    startRecurringTimer(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAgent(agentId: string, active: boolean): Promise<void>;
    updateCloneProtection(settings: CloneProtectionSettings): Promise<void>;
}
import type { Agent as _Agent, AgentType as _AgentType, AppLicense as _AppLicense, AutomationStatus as _AutomationStatus, ContentType as _ContentType, KnowledgeEntry as _KnowledgeEntry, LicenseType as _LicenseType, Offer as _Offer, OfferPerformanceMetrics as _OfferPerformanceMetrics, Reference as _Reference, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLaunch(arg0: string, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLaunch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLaunch(arg0, arg1);
            return result;
        }
    }
    async addOffer(arg0: string, arg1: bigint, arg2: number, arg3: Time, arg4: Time | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOffer(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOffer(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addOfferMetrics(arg0: string, arg1: bigint, arg2: number, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOfferMetrics(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOfferMetrics(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAgent(arg0: AgentType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgent(to_candid_AgentType_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgent(to_candid_AgentType_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createAppLicense(arg0: LicenseType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppLicense(to_candid_LicenseType_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppLicense(to_candid_LicenseType_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAgent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAgent(arg0);
            return result;
        }
    }
    async getAgent(arg0: string): Promise<Agent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentLogs(arg0: AgentType): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentLogs(to_candid_AgentType_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentLogs(to_candid_AgentType_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllAgentLogs(): Promise<{
        habit: Array<LogEntry>;
        copy: Array<LogEntry>;
        analytics: Array<LogEntry>;
        affiliate: Array<LogEntry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgentLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgentLogs();
            return result;
        }
    }
    async getAllAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgents();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgents();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAppLicenses(): Promise<Array<AppLicense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppLicenses();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppLicenses();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAutomationStatuses(): Promise<Array<[AgentType, AutomationStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAutomationStatuses();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAutomationStatuses();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllKnowledgeEntries(): Promise<Array<KnowledgeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKnowledgeEntries();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKnowledgeEntries();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLaunches(): Promise<Array<LaunchRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLaunches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLaunches();
            return result;
        }
    }
    async getAllOfferMetrics(): Promise<Array<OfferPerformanceMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOfferMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOfferMetrics();
            return result;
        }
    }
    async getAllOffers(): Promise<Array<Offer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOffers();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOffers();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAutomationStatus(arg0: AgentType): Promise<AutomationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getAutomationStatus(to_candid_AgentType_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AutomationStatus_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAutomationStatus(to_candid_AgentType_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AutomationStatus_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAgents();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAgents();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAppLicense(): Promise<AppLicense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAppLicense();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAppLicense();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerKnowledgeEntries(): Promise<Array<KnowledgeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerKnowledgeEntries();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerKnowledgeEntries();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClickCountPerOffer(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClickCountPerOffer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClickCountPerOffer();
            return result;
        }
    }
    async getCloneProtectionSettings(): Promise<CloneProtectionSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getCloneProtectionSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCloneProtectionSettings();
            return result;
        }
    }
    async getCollaborationStats(): Promise<Array<[AgentType, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollaborationStats();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollaborationStats();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversionRatePerOffer(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversionRatePerOffer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversionRatePerOffer();
            return result;
        }
    }
    async getIsStripeReady(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getIsStripeReady();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIsStripeReady();
            return result;
        }
    }
    async getKnowledgeEntry(arg0: string): Promise<KnowledgeEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKnowledgeEntry(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKnowledgeEntry(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfferMetrics(arg0: string): Promise<OfferPerformanceMetrics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfferMetrics(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfferMetrics(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfferPerformanceSummary(): Promise<{
        totalOffers: bigint;
        revenueTotals: bigint;
        conversionRates: Array<[string, number]>;
        allMetrics: Array<OfferPerformanceMetrics>;
        clickCounts: Array<[string, bigint]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfferPerformanceSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfferPerformanceSummary();
            return result;
        }
    }
    async getRevenueTotals(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueTotals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueTotals();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalActiveOffers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalActiveOffers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalActiveOffers();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async initStripe(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initStripe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initStripe(arg0);
            return result;
        }
    }
    async isActiveUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isActiveUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isActiveUser();
            return result;
        }
    }
    async isAuthorizedClone(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthorizedClone();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthorizedClone();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOwnerCertified(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOwnerCertified();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOwnerCertified();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async runAffiliateAgent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runAffiliateAgent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAffiliateAgent();
            return result;
        }
    }
    async runAgent(arg0: AgentType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runAgent(to_candid_AgentType_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAgent(to_candid_AgentType_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async runAgentId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runAgentId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAgentId(arg0);
            return result;
        }
    }
    async runAllAgents(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runAllAgents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAllAgents();
            return result;
        }
    }
    async runAnalyticsAgent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runAnalyticsAgent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAnalyticsAgent();
            return result;
        }
    }
    async runCollaborationLoop(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runCollaborationLoop();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runCollaborationLoop();
            return result;
        }
    }
    async runCopyAgent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runCopyAgent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runCopyAgent();
            return result;
        }
    }
    async runHabitAgent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runHabitAgent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runHabitAgent();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async startRecurringTimer(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startRecurringTimer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startRecurringTimer();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAgent(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgent(arg0, arg1);
            return result;
        }
    }
    async updateCloneProtection(arg0: CloneProtectionSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCloneProtection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCloneProtection(arg0);
            return result;
        }
    }
}
function from_candid_AgentType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentType): AgentType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Agent_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Agent {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_AppLicense_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppLicense): AppLicense {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_AutomationStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutomationStatus): AutomationStatus {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_KnowledgeEntry_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnowledgeEntry): KnowledgeEntry {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_LicenseType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LicenseType): LicenseType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Offer_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Offer): Offer {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Reference_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reference): Reference {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppLicense]): AppLicense | null {
    return value.length === 0 ? null : from_candid_AppLicense_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KnowledgeEntry]): KnowledgeEntry | null {
    return value.length === 0 ? null : from_candid_KnowledgeEntry_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OfferPerformanceMetrics]): OfferPerformanceMetrics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Agent]): Agent | null {
    return value.length === 0 ? null : from_candid_Agent_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    active: boolean;
    owner: Principal;
    agentType: _AgentType;
    lastRun: bigint;
}): {
    id: string;
    active: boolean;
    owner: Principal;
    agentType: AgentType;
    lastRun: bigint;
} {
    return {
        id: value.id,
        active: value.active,
        owner: value.owner,
        agentType: from_candid_AgentType_n11(_uploadFile, _downloadFile, value.agentType),
        lastRun: value.lastRun
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [_Time];
    purchaseTime: _Time;
    owner: Principal;
    licenseType: _LicenseType;
}): {
    expiresAt?: Time;
    purchaseTime: Time;
    owner: Principal;
    licenseType: LicenseType;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.expiresAt)),
        purchaseTime: value.purchaseTime,
        owner: value.owner,
        licenseType: from_candid_LicenseType_n18(_uploadFile, _downloadFile, value.licenseType)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalExecutions: bigint;
    lastRun: [] | [_Time];
    running: boolean;
}): {
    totalExecutions: bigint;
    lastRun?: Time;
    running: boolean;
} {
    return {
        totalExecutions: value.totalExecutions,
        lastRun: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.lastRun)),
        running: value.running
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    references: Array<_Reference>;
    content: string;
    contentType: _ContentType;
    owner: Principal;
    sourceAgent: _AgentType;
    timestamp: _Time;
}): {
    id: string;
    references: Array<Reference>;
    content: string;
    contentType: ContentType;
    owner: Principal;
    sourceAgent: AgentType;
    timestamp: Time;
} {
    return {
        id: value.id,
        references: from_candid_vec_n27(_uploadFile, _downloadFile, value.references),
        content: value.content,
        contentType: from_candid_ContentType_n30(_uploadFile, _downloadFile, value.contentType),
        owner: value.owner,
        sourceAgent: from_candid_AgentType_n11(_uploadFile, _downloadFile, value.sourceAgent),
        timestamp: value.timestamp
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    refType: _ContentType;
    refId: string;
}): {
    refType: ContentType;
    refId: string;
} {
    return {
        refType: from_candid_ContentType_n30(_uploadFile, _downloadFile, value.refType),
        refId: value.refId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: [] | [_Time];
    productId: string;
    commissionRate: number;
    priceInCents: bigint;
    startDate: _Time;
}): {
    id: string;
    endDate?: Time;
    productId: string;
    commissionRate: number;
    priceInCents: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.endDate)),
        productId: value.productId,
        commissionRate: value.commissionRate,
        priceInCents: value.priceInCents,
        startDate: value.startDate
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_tuple_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_AgentType, _AutomationStatus]): [AgentType, AutomationStatus] {
    return [
        from_candid_AgentType_n11(_uploadFile, _downloadFile, value[0]),
        from_candid_AutomationStatus_n22(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_AgentType, bigint]): [AgentType, bigint] {
    return [
        from_candid_AgentType_n11(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    habit: null;
} | {
    copy: null;
} | {
    analytics: null;
} | {
    affiliate: null;
}): AgentType {
    return "habit" in value ? AgentType.habit : "copy" in value ? AgentType.copy : "analytics" in value ? AgentType.analytics : "affiliate" in value ? AgentType.affiliate : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    demo: null;
} | {
    full: null;
}): LicenseType {
    return "trial" in value ? LicenseType.trial : "demo" in value ? LicenseType.demo : "full" in value ? LicenseType.full : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    performanceData: null;
} | {
    strategy: null;
} | {
    insight: null;
} | {
    recommendation: null;
}): ContentType {
    return "performanceData" in value ? ContentType.performanceData : "strategy" in value ? ContentType.strategy : "insight" in value ? ContentType.insight : "recommendation" in value ? ContentType.recommendation : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n48(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Array<Agent> {
    return value.map((x)=>from_candid_Agent_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppLicense>): Array<AppLicense> {
    return value.map((x)=>from_candid_AppLicense_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_AgentType, _AutomationStatus]>): Array<[AgentType, AutomationStatus]> {
    return value.map((x)=>from_candid_tuple_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KnowledgeEntry>): Array<KnowledgeEntry> {
    return value.map((x)=>from_candid_KnowledgeEntry_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reference>): Array<Reference> {
    return value.map((x)=>from_candid_Reference_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Offer>): Array<Offer> {
    return value.map((x)=>from_candid_Offer_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_AgentType, bigint]>): Array<[AgentType, bigint]> {
    return value.map((x)=>from_candid_tuple_n43(_uploadFile, _downloadFile, x));
}
function to_candid_AgentType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentType): _AgentType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_LicenseType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LicenseType): _LicenseType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentType): {
    habit: null;
} | {
    copy: null;
} | {
    analytics: null;
} | {
    affiliate: null;
} {
    return value == AgentType.habit ? {
        habit: null
    } : value == AgentType.copy ? {
        copy: null
    } : value == AgentType.analytics ? {
        analytics: null
    } : value == AgentType.affiliate ? {
        affiliate: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LicenseType): {
    trial: null;
} | {
    demo: null;
} | {
    full: null;
} {
    return value == LicenseType.trial ? {
        trial: null
    } : value == LicenseType.demo ? {
        demo: null
    } : value == LicenseType.full ? {
        full: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
